// Svelte/polls/src/App.svelte
<script>
	import Header from "./components/Header.svelte";
	import Footer from "./components/Footer.svelte";
	import CreateNewPoll from "./components/CreateNewPoll.svelte";
	import Router from 'svelte-spa-router';
	import About from "./components/About.svelte";
	import Home from "./components/Home.svelte";

	const routes = {
		'/': Home,
		'/about': About,
        '/create': CreateNewPoll,
	};

</script>

<main>
    <Header />
        <Router {routes} />
    <Footer />
</main>

<style>


</style>

// React/mario-blog/src/App.js
import Navbar from "./Navbar";
import Home from "./Home";
import About from "./About";
import {Route, Routes} from "react-router-dom";
import Create from "./Create";

function App() {
	
	return (
		<div className="App">
			<Navbar />
			<div className="content">
				<Routes>
					<Route path="/" element={<Home />} />
					<Route path="/about" element={<About />} />
					<Route path="/create" element={<Create />} />
				</Routes>
			</div>
		</div>
	);
}

export default App;
